#!/bin/bash

config=$KUBECONFIG

[ -z "$config" ] && config="$HOME/.bp/config"
[ ! -f $config ] && { echo "not exist"; exit 1; }

current=$(bpctl contexts list|grep '*')
[[ $? -ne 0 ]] && exit 1

ctx=$(echo "$current"|awk '{print $2}')
ns=$(echo "$current"|awk '{print $3}')

echo "$ctx/$ns"
